---
title: "SPARQL"
title-slide-attributes:
  data-background-color: "#B5E2FF"
format:
  # html: default
  revealjs:
    # mainfont: "Alegreya Sans"
    fontsize: 24px
    css: /styles.css
    # output-file: slides_space.html
    footer: "[atRium](https://aiscr.cz/atRium/) *training school*, Brno 2024 | [SPARQL](/sparql/index.qmd)"
    logo: /figs/Clay.png
    chalkboard:
      theme: whiteboard
      chalk-effect: 0.0
  # pdf: default
execute:
  echo: true
  warning: false
  cache: true
callout-appearance: simple
callout-icon: false
---

## Introduction to SPARQL {.center background-color="#FAF1A4"}

### *SPARQL Protocol and RDF Query Language*


## SPARQL 

- SPARQL is a query language for RDF data.
- SPARQL is a recursive acronym for *SPARQL Protocol and RDF Query Language*.
- [W3C standard](http://www.w3.org/TR/sparql11-query/).

### Types of queries 

- `ASK` query -- returns true/false answer.
- **`SELECT` query** -- returns list (table) of results.
- `DESCRIBE` query -- returns all possible information about an entity.
- `CONSTRUCT` query -- returns new set of triples.


## SPARQL query 

- Consists of **triple patterns** with **zero or more variables**.
- Variables are prefixed with a question mark (`?variableName`).
- Triple patterns are matched against the triples in the graph.
- Each matching triple produces one result.

`?subject ?predicate ?object .`

### Common abbreviations 

- subject as `?s`
- predicate/property as `?p`
- object as `?o`


## SELECT query 

```{.sql}
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT ?label

FROM <SPARQL endpoint>

WHERE {
  ?subject ?predicate ?ooject .
  ?oobject rdfs:label ?label
}

LIMIT 100
```

**Parts of the query** 

- `PREFIX`: Namespace definition -- prefixes.
- `SELECT`: Selected variables -- will be in the output as column names.
- `FROM`: Specification of the graph from which we are querying.
- `WHERE`: Where clause with triple patterns to be matched in the graph.
- `LIMIT`: Limits the number of returned results (so we do not overload the endpoint).


## Example query {background-color="#CDFFB5"}

### DBpedia

Find all other URIs/IRIs that Ariadne maps to in DBpedia.

```{.sql}
PREFIX dbr: <http://dbpedia.org/resource/>
PREFIX owl: <http://www.w3.org/2002/07/owl#>

SELECT ?o

FROM <http://dbpedia.org>

WHERE {
  dbr:Ariadne owl:sameAs ?o .
}

LIMIT 100
```

Query in [DBpedia](https://dbpedia.org/sparql?default-graph-uri=http%3A%2F%2Fdbpedia.org&qtxt=PREFIX%20dbr%3A%20%3Chttp%3A%2F%2Fdbpedia.org%2Fresource%2F%3E%0APREFIX%20owl%3A%20%3Chttp%3A%2F%2Fwww.w3.org%2F2002%2F07%2Fowl%23%3E%0A%0ASELECT%20%3Fo%0A%0AFROM%20%3Chttp%3A%2F%2Fdbpedia.org%3E%0A%0AWHERE%20%7B%0Adbr%3AAriadne%20owl%3AsameAs%20%3Fo%20.%0A%7D%0A%0ALIMIT%20100&format=text%2Fhtml&timeout=10000&signal_void=on&signal_unconnected=on).


## Example query {background-color="#CDFFB5"}

### DBpedia

Find peole (and the dates they were born and died) who had to do anything with archaeology according to DBpedia.

```{.sql}
PREFIX dbr: <http://dbpedia.org/resource/>
PREFIX dbo: <http://dbpedia.org/ontology/>

SELECT ?s ?born ?died

FROM <http://dbpedia.org>

WHERE {
  ?s ?p dbr:Archaeology .
  ?s dbo:birthDate ?born .
  ?s dbo:deathDate ?died .
}

ORDER BY ASC (?born)
LIMIT 100
```

Query in [DBpedia](https://dbpedia.org/sparql?default-graph-uri=http%3A%2F%2Fdbpedia.org&qtxt=PREFIX%20dbr%3A%20%3Chttp%3A%2F%2Fdbpedia.org%2Fresource%2F%3E%0APREFIX%20dbo%3A%20%3Chttp%3A%2F%2Fdbpedia.org%2Fontology%2F%3E%0A%0ASELECT%20%3Fs%20%3Fborn%20%3Fdied%0A%0AFROM%20%3Chttp%3A%2F%2Fdbpedia.org%3E%0A%0AWHERE%20%7B%0A%20%20%3Fs%20%3Fp%20dbr%3AArchaeology%20.%0A%20%20%3Fs%20dbo%3AbirthDate%20%3Fborn%20.%0A%20%20%3Fs%20dbo%3AdeathDate%20%3Fdied%20.%0A%7D%0A%0AORDER%20BY%20ASC%20(%3Fborn)%0ALIMIT%20100&format=text%2Fhtml&timeout=10000&signal_void=on&signal_unconnected=on).

- `ORDER BY ASC` orders the results in an ascending order of the given variable.


## Example query {background-color="#CDFFB5"}

### DBpedia

How many  are there?

```{.sql}
PREFIX dbr: <http://dbpedia.org/resource/>

SELECT (COUNT(?s) AS ?count)

FROM <http://dbpedia.org>

WHERE {
  ?s ?p dbr:Archaeology .
}
```

Query in [DBpedia](https://dbpedia.org/sparql?default-graph-uri=http%3A%2F%2Fdbpedia.org&qtxt=PREFIX%20dbr%3A%20%3Chttp%3A%2F%2Fdbpedia.org%2Fresource%2F%3E%0A%0ASELECT%20(COUNT(%3Fs)%20AS%20%3Fcount)%0A%0AFROM%20%3Chttp%3A%2F%2Fdbpedia.org%3E%0A%0AWHERE%20%7B%0A%20%20%3Fs%20%3Fp%20dbr%3AArchaeology%20.%0A%7D&format=text%2Fhtml&timeout=10000&signal_void=on&signal_unconnected=on).

- `COUNT(?variable) AS ?result` counts the number of returned matches.


## Example query {background-color="#CDFFB5"}

### Wikidata 

How many archaeologists are there in Wikidata?

```{.sql}
PREFIX wd: <http://www.wikidata.org/entity/>
PREFIX wdt: <http://www.wikidata.org/prop/direct/>

SELECT (COUNT(?ae) AS ?count)

WHERE {
  ?ae wdt:P31 wd:Q5 .
  ?ae wdt:P106 wd:Q3621491 .
}
```

Query in [Wikidata Query Service](https://query.wikidata.org/#PREFIX%20wd%3A%20%3Chttp%3A%2F%2Fwww.wikidata.org%2Fentity%2F%3E%0APREFIX%20wdt%3A%20%3Chttp%3A%2F%2Fwww.wikidata.org%2Fprop%2Fdirect%2F%3E%0ASELECT%20%28COUNT%28%3Fae%29%20AS%20%3Fcount%29%0AWHERE%20%7B%0A%20%20%3Fae%20wdt%3AP31%20wd%3AQ5%20.%0A%20%20%3Fae%20wdt%3AP106%20wd%3AQ3621491%20.%0A%7D). 


## Example query {background-color="#CDFFB5"}

### Wikidata 

Return a list of archaeologists, their sex/gender, and the dates they were born and died.

```{.sql}
PREFIX wd: <http://www.wikidata.org/entity/>
PREFIX wdt: <http://www.wikidata.org/prop/direct/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT ?ae ?label ?sex ?born ?died

WHERE {
  ?ae wdt:P31 wd:Q5 ;
    wdt:P106 wd:Q3621491 ;
    rdfs:label ?label ;
    wdt:P21 ?o ;
    wdt:P569 ?born ;
    wdt:P570 ?died ;
  ?o rdfs:label ?sex .
  
  FILTER (lang(?label) = 'en')
  FILTER (lang(?sex) = 'en')
}

LIMIT 200
```

Query in [Wikidata Query Service](https://query.wikidata.org/#PREFIX%20wd%3A%20%3Chttp%3A%2F%2Fwww.wikidata.org%2Fentity%2F%3E%0APREFIX%20wdt%3A%20%3Chttp%3A%2F%2Fwww.wikidata.org%2Fprop%2Fdirect%2F%3E%0APREFIX%20rdfs%3A%20%3Chttp%3A%2F%2Fwww.w3.org%2F2000%2F01%2Frdf-schema%23%3E%0A%0ASELECT%20%3Fae%20%3Flabel%20%3Fsex%20%3Fborn%20%3Fdied%0A%0AWHERE%20%7B%0A%20%20%3Fae%20wdt%3AP31%20wd%3AQ5%20.%0A%20%20%3Fae%20wdt%3AP106%20wd%3AQ3621491%20.%0A%20%20%3Fae%20rdfs%3Alabel%20%3Flabel%20.%0A%20%20%3Fae%20wdt%3AP21%20%3Fo%20.%0A%20%20%3Fae%20wdt%3AP569%20%3Fborn%20.%0A%20%20%3Fae%20wdt%3AP570%20%3Fdied%20.%0A%20%20%3Fo%20rdfs%3Alabel%20%3Fsex%20.%0A%20%20%0A%20%20FILTER%20%28lang%28%3Flabel%29%20%3D%20%27en%27%29%0A%20%20FILTER%20%28lang%28%3Fsex%29%20%3D%20%27en%27%29%0A%7D%0A%0ALIMIT%20200). 

- `FILTER (lang(?label) = 'en')` returns only labels in English.


## Example query {background-color="#CDFFB5"}

### Wikidata 

Count all archaeological *artefacts* and archaeological *finds* in Wikidata.

```{.sql}
PREFIX wd: <http://www.wikidata.org/entity/>
PREFIX wdt: <http://www.wikidata.org/prop/direct/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT 
(COUNT(?a) AS ?artifacts)
(COUNT(?f) AS ?finds)

WHERE {
  #?a wdt:P31 wd:Q220659 .
  ?f wdt:P31 wd:Q10855061 .
}
```

Query in [Wikidata Query Service]().


## ARIADNE SPARQL Endpoint


## SPARQL in R {.center background-color="#FAF1A4"}

### *How to query SPARQL endpoints from R*


## SPARQL in R 










##

```{.sql}
SELECT ?label
WHERE {
  ?s rdf:origin dbo:Crete .
  ?s rdf:label ?label .
}
```



```{.sql}
SELECT ?label
WHERE {
  ?s dbo:origin dbr:Crete .
  ?s rdf:type dbo:MythicalFigure .
  ?s rdf:label ?label .
}
```



## Ex 

```{.sql}
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX dbr: <http://dbpedia.org/resource/>
PREFIX dbo: <http://dbpedia.org/ontology/>
PREFIX dbp: <http://dbpedia.org/property/>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>

SELECT ?s ?label

WHERE {
  ?s a foaf:Person .
  ?s dbo:academicDiscipline dbr:Archaeology .
  ?s rdfs:label ?label .
  
  FILTER (lang(?label) = 'en')
}

LIMIT 100
```

[Query](https://dbpedia.org/sparql?default-graph-uri=http%3A%2F%2Fdbpedia.org&qtxt=PREFIX%20rdf%3A%20%3Chttp%3A%2F%2Fwww.w3.org%2F1999%2F02%2F22-rdf-syntax-ns%23%3E%0APREFIX%20rdfs%3A%20%3Chttp%3A%2F%2Fwww.w3.org%2F2000%2F01%2Frdf-schema%23%3E%0APREFIX%20dbr%3A%20%3Chttp%3A%2F%2Fdbpedia.org%2Fresource%2F%3E%0APREFIX%20dbo%3A%20%3Chttp%3A%2F%2Fdbpedia.org%2Fontology%2F%3E%0APREFIX%20dbp%3A%20%3Chttp%3A%2F%2Fdbpedia.org%2Fproperty%2F%3E%0APREFIX%20foaf%3A%20%3Chttp%3A%2F%2Fxmlns.com%2Ffoaf%2F0.1%2F%3E%0A%0ASELECT%20%3Fs%20%3Flabel%0A%0AWHERE%20%7B%0A%20%20%3Fs%20a%20foaf%3APerson%20.%0A%20%20%3Fs%20dbo%3AacademicDiscipline%20dbr%3AArchaeology%20.%0A%20%20%3Fs%20rdfs%3Alabel%20%3Flabel%20.%0A%20%20%0A%20%20FILTER%20(lang(%3Flabel)%20%3D%20'en')%0A%7D%0A%0ALIMIT%20100&format=text%2Fhtml&timeout=30000&signal_void=on&signal_unconnected=on)
