project:
  type: website

website:
  title: "atRium Training School"
  navbar:
    logo: figs/BrandmarkSunbleached.png
    background: "#A6503E"
    foreground: "#E8DAC8"
    pinned: true
    left:
      - href: index.qmd
        text: Home
        icon: house-door
      - href: info.qmd
        text: General info
        icon: info-circle
      - href: applications.qmd
        text: Applications
        icon: envelope-paper
      - href: programme.qmd
        text: Programme
        icon: calendar4
      - href: materials.qmd
        text: Materials
        icon: book
    right: 
      - href: about.qmd
        text: About
        icon: people
  page-footer: 
    background: "#3A3736"
    foreground: "#E8DAC8"
    left: 
      - href: https://www.quarto.org/
        text: "Build with &#9825; in Quarto."
    center:
      - text: "Licenses: MIT (code) & CC BY-SA 4.0 Int. (other content)."
    right: 
      - icon: github
        href: https://github.com/petrpajdla/atRium
  repo-url: https://github.com/petrpajdla/atRium
  repo-actions: [source, edit, issue]
  back-to-top-navigation: false

format:
  html:
    theme: cosmo
    mainfont: Barlow
    css: styles.css
    toc: true
    link-external-newwindow: true
    header-includes: |
      <link href="https://fonts.googleapis.com/css2?family=Barlow:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap" rel="stylesheet">
