project:
  type: website

website:
  title: "atRium Training School"
  navbar:
    left:
      - href: index.qmd
        text: Home
        icon: house-door
      - href: info.qmd
        text: General info
        icon: info-circle
      - href: applications.qmd
        text: Applications
        icon: envelope-paper
      - href: programme.qmd
        text: Programme
        icon: calendar4
      # - href: materials.qmd
      #   text: Materials
      #   icon: book
    right:
      - href: about.qmd
        text: About
        icon: people
  page-footer: 
    # background: "#F2F3F4"
    left: 
      - href: https://quarto.org/
        text: "Build with quarto."
    center:
      - text: "Licenses: MIT (code) & CC BY-SA 4.0 Int. (other content)."
    right: 
      - icon: github
        href: https://github.com/petrpajdla/atRium
  repo-url: https://github.com/petrpajdla/atRium
  repo-actions: [source, edit, issue]
  back-to-top-navigation: true

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
