---
title: "Applications"
---

<!-- ::: {.callout-note}
Apply using the online form [here](https://docs.google.com/forms/d/e/1FAIpQLSctI5Dw7VhUmVKQxSj7lPwGWCvEKU3oI5YlRi0Y1MihDKTXGg/viewform).
::: -->

More details about the transnational access scheme grants can be found on the [ATRIUM Project website](https://atrium-research.eu/travel-grants/){.external}.

## Key dates 

|                               |                                |
|-----------------------------  |--------------------------------|
| April 2024                    | Call for participants opens    |
| **31 May 2024**               | **Deadline for applications**  |
| 28 June 2024                  | Acceptance notifications sent before this date |
| **16--20 September 2024**     | **Training school**            |
| mid-October 2024 (?)          | Deadline for submission of reports |
| end of November 2024          | Grants paid before this date   |

: {tbl-colwidths="[30,70]"}

<!-- ::: -->

## Who should apply

::: {.callout-tip}

## Note

Only applicants with institutional affiliation **outside of the Czech Republic** are eligible to receive funding due to the *trans-national* nature of the access to the infrastructure provided by the school.
:::

We welcome applications from early-career researchers and PhD students who are enthusiastic about acquiring programming skills, particularly in the R scripting language, to efficiently retrieve and analyse extensive (spatial) datasets. 
Participants should demonstrate a keen interest in conducting data analysis and processing in a structured and reproducible manner using scripting languages. 

While applicants with prior knowledge of R programming are encouraged to apply, the first day of the training will be dedicated to mastering the fundamentals of R. 
Individuals who are complete beginners are welcome as well, as no prior experience is necessary. 
Additionally, applicants should have a basic understanding of statistics, data management, and geographic information systems to fully benefit from the training.


## How to apply

Submit your applications through an [**online form**](https://docs.google.com/forms/d/e/1FAIpQLSctI5Dw7VhUmVKQxSj7lPwGWCvEKU3oI5YlRi0Y1MihDKTXGg/viewform){.external}. 
On the 4th page of the application (*TNA Scheme*), choose **'Summer School Access'** and **'Archaeological Information System of the Czech Republic, Institute of Archaeology of the Czech Academy of Sciences, Brno -- AIS CR (ARUB)'** as the proposed host organisation.
On the next page (*Summer School Application*) please explain why you believe this training would be valuable for your research and how you intend to integrate these newfound skills into your work.

More details on how to apply can be found [here](https://atrium-research.eu/tna-application-process/){.external}.
