---
title: "General Information"
---

## Date and venue

The school takes place from **16th to 20th September 2024** and it is held at the premises of the **Institute of Archaeology, Czech Academy of Sciences, Brno** (<https://arub.cz/>), the address is:

> Čechyňská 363/19  
> 602 00 Brno  
> Czech Republic

::: {.callout-note}
Remote participation is **not** possible!
This is an in-person event only.
:::

```{r}
#| echo: false
library(leaflet)
arub <- c(16.6208208, 49.1892306)
popup <- paste0("Here!")
leaflet() %>% 
  addTiles() %>% 
  setView(lng = arub[1], lat = arub[2], zoom = 15) %>% 
  addMarkers(lng = arub[1], lat = arub[2], popup = popup)
```

## Grants

Each participant of the school is eligible to receive *around* 1,400 Euro to cover travel expenses, housing, and daily subsistence during the meeting. 
To receive the grant, participants need to:

1. **Apply via official form** of the ATRIUM project (see section [Applications](applications.qmd) for details) containing personal details, motivation for participation and a short project proposal.
2. **Participate in person**, i.e. sign attendance sheets for each day of the school.
3. **Submit a report** within a given time frame after the school with details on the participation and progress on the project they worked on.

## Other information

### Travelling to Brno

Brno is easily reachable by trains or buses from Prague (approx 2 -- 2.5 hour journey) and Vienna (approx. 1.5 -- 2 hour journey). 
Many overnight trains crossing large part of Europe start or end in Vienna and we recommend taking these trains as an alternative to flying.

<!-- ### Accommodation -->

<!-- No accommodation is provided to participants. -->
<!-- Please arrange your accommodation in one of many cities hotels or hostels. -->
<!-- We will add some tips for places close to the venue. -->

<!-- ### Food -->
