---
title: "Materials and data"
---

::: {.callout-note}
## Note 

The online presentations in HTML can be downloaded in PDF:  

- open the presentation, 
- press `e` or the three lines in the left bottom corner, `Tools` and `PDF Export Mode`,
- print the result to PDF using your browser.
:::

## Monday, 16 Sept.

#### Introduction to R

- [Presentation](/intro2r/index.qmd) contents:
    - [Functions and data structures](/intro2r/index.qmd#/functions-and-syntax)
    - Basic [workflows](/intro2r/index.qmd#/workflow-1) (packages, scripts, projects, paths)
    - [Reading](/intro2r/index.qmd#/loading-data) data into R
- Dataset [dartpoints.csv](/data/dartpoints.csv)

#### Data analysis and data viz

- [Presentation](/dataviz/index.qmd)


## Tuesday, 17 Sept.

#### Linked Open Data & ARIADNE

- [Presentation](/ariadne/index.qmd) contents: 
    - [ARIADNE Portal](/ariadne/index.qmd#/ariadne)
    - [Linked Open Data (LOD)](/ariadne/index.qmd#/linked-open-data)
    - [AO-Cat ontology](ariadne/index.qmd#/ao-cat-ontology)

#### SPARQL 

- [Presentation](/sparql/index.qmd) contents:
    - [Intro](/sparql/index.qmd#/introduction-to-sparql) to `SPARQL`
    - Examples of `SPARQL` queries on [DBpedia](/sparql/index.qmd#/dbpedia-virtuoso-query-service), [Wikidata](/sparql/index.qmd#/wikidata-query-service) and [ARIADNE GraphDB](/sparql/index.qmd#/ariadne-knowledge-base)
    - `SPARQL` [queries from `R`](/sparql/index.qmd#/sparql-queries-in-r) using [`glitter`](/sparql/index.qmd#/glitter-1) package
- [`R` script `wikidata.r`](/sparql/wikidata.r) with Wikidata exercise
- [`R` script `ariadne.r`](/sparql/ariadne.r) with ARIADNE exercise

#### Resources 

- Article [*Practices of Linked Open Data in Archaeology and Their Realisation in Wikidata*](https://doi.org/10.3390/digital2030019) by Sophie C. Schmid, Florian Thiery and Martina Trognitz
- [*AO-Cat ontology*](https://zenodo.org/doi/10.5281/zenodo.7818374)
- [*Introduction to the Principles of LOD*](https://doi.org/10.46430/phen0068) on Programming Historian
- [*Using SPARQL to access Linked Open Data*](https://doi.org/10.46430/phen0047) on Programming Historian


## Wednesday, 18 Sept.

#### Intro to spatial data

- [R script](spatial/install_packages.R) with required packages.
- [R script](spatial/spatial_is_special.R) with the spatial analysis.

(Data circulated on a USB stick.)


## Thursday, 19 Sept.

- [Presentation (PPTX)](spatial/PPA_intro_kempf.pptx) on the point pattern analysis.
- [R script](spatial/ppa.R) with the point pattern analysis.

#### Note on `setwd()`

- [Blog post](https://www.tidyverse.org/blog/2017/12/workflow-vs-script/) by Jenny Bryan why not to hardcode `setwd()` into your scripts and what is the alternative.
- Also check the [Intro to R presentation from Monday](intro2r/#/loading-data), where relative paths and project oriented workflow is explained a bit.


## Friday, 20 Sept.

#### R books

- [*R for Data Science*](https://r4ds.hadley.nz/) by Hadley Wickham, Mine Çetinkaya-Rundel and Garrett Grolemund -- `tidyverse` packages, data manipulation, visualization etc.
- [*Geocomputation with R*](https://r.geocompx.org/) by Robin Lovelace, Jakub Nowosad, and Jannes Muenchow -- `sf`, `terra` and other spatial packages.
- [*Spatial Data Science*](https://r-spatial.org/book/) by Edzer Pebesma and Roger Bivand -- includes more advanced topics like point pattern analysis with `spatstat` etc.
- [*Data Visualization. A practical introduction*](https://socviz.co/) by Kieran Healy -- gives you all you need to be able to create beautiful plots with `ggplot2`.


##### Some more `glitter` and ARIADNE 

- [`R` script](/sparql/friday.r) with an example query on coins from ARIADNE SPARQL endpoint.
